### ISSUE TITLE
Eagle files

### ISSUE THREAD

**Issue by giaava** [mistay/stknx#1]
Thank you for sharing the example.
please, can you share also the eagle files and the component list?
Thank you again

**Comment by mistay** [comment]
sure

**Comment by mistay** [comment]
[esp32_knx_onewire_v0.3.zip](https://github.com/mistay/stknx/files/3818594/esp32_knx_onewire_v0.3.zip)
[esp32_knx_onewire_gerbers_v0.3.zip](https://github.com/mistay/stknx/files/3818595/esp32_knx_onewire_gerbers_v0.3.zip)

**Comment by mistay** [comment]
so please keep in mind that it's used to acquire temperature values by onewire bus (ds18s20) and send them via stknx to the knx bus.

**Comment by giaava** [comment]
Thank You very much, you has been very kind.
The project I want to realize is very similar to your and your example is a good start point.
Thank you again.

**Comment by giaava** [comment]
Hi, I have seen the project, but I would like to use the STKNX and not the TP-UART.
Please, be so kind ti share the STKNX version.
Thank You Again.

**Comment by mistay** [comment]
you can use either tpuart or stnknx, whatever you prefer. please have another look, it's all in.

**Comment by giaava** [comment]
Sorry, may be I am wrong, but I see only two pages in schematics that you posted; in the pdf inside git there are four pages and, in the third, there is the STKNX schematic

**Comment by giaava** [comment]
This is the schematic you sent.
Thank you again.
[esp32_knx_onewire_schematic.pdf](https://github.com/mistay/stknx/files/3835379/esp32_knx_onewire_schematic.pdf)

**Comment by mistay** [comment]
[esp32_knx_onewire-v0.10_cleanup.zip](https://github.com/mistay/stknx/files/3843668/esp32_knx_onewire-v0.10_cleanup.zip)

sorry sent an outdated version. this one is the one you requested.

**Comment by mistay** [comment]
[esp32_knx_onewire_gerbers-v0.10.zip](https://github.com/mistay/stknx/files/3843673/esp32_knx_onewire_gerbers-v0.10.zip)

and here you have the gerber files (just if you'd like to produce some more boards)

**Comment by giaava** [comment]
Thank you, this is very useful to me.
